### ISSUE TITLE
ChromeDriver download script is broken

### ISSUE THREAD

**Issue by jossjacobo** [conductor-framework/conductor#16]
On the WebDrier-Executables Wiki Page, under ChromeDriver and Mac Installation, the download script is broken.

https://gist.githubusercontent.com/ddavison/936d843ad17140021fad/raw/Mac.sh

The script has name hardcoded to `chromedriver_mac32.zip` instead of using the `key` param of the latest build.

**Comment by ddavison** [comment]
thanks @jossjacobo , looks like they stopped updating their [`LATEST_RELEASE` file](https://chromedriver.storage.googleapis.com/LATEST_RELEASE) which is what I was using before.  I've updated the wiki page, and tweaked the shell scripts to point to a specific version for now, that way I can control which version of ChromeDriver is downloaded. I think this is safest anyway since newer chromedriver executables sometime conflict with the selenium bindings.

i'm sort of limited right now, in the fact that I am not using the `<Key>` as you stated, but that's definitely subject to change.

thanks for letting me know!
