### ISSUE TITLE
Locomotive with PageObject pattern?

### ISSUE THREAD

**Issue by Alexeggers** [conductor-framework/conductor#29]
Hi,

I am currently learning about writing Selenium Integration Tests, and came across the PageObject design pattern (https://github.com/SeleniumHQ/selenium/wiki/PageObjects). I like the idea of extracting individual page behaviour and build a PageObject class extending Locomotive. My colleagues have voices concerns that your library is meant to extend the test class, rather than objects within it. For context, I am only a trainee at the moment, so please feel free to point out obvious mistakes in my reasoning.

I find your library incredibly convenient to use, but am now unsure whether I should use it with this pattern. Can you provide some guidance on this?

Much Appreciated,
Alex

**Comment by ddavison** [comment]
Hi @Alexeggers, I've built very successful and maintainable selenium infrastructures before with no PageObject patterns.  

Conductor uses the style that I've found very successful, and that's having a java class for each page.

```
project/
  src/main/java/helpers/
    pages/
      LoginPage
      HomePage
      RegistrationPage
      ...
    layers/
      PopupLayer
...
```

One mechanism that Conductor doesn't give by default, but it easily extendable, is to present an interface like this:

```java
@Test
public void main test() {
  setText(LoginPage.txtUsername, "username")
  .setText(LoginPage.txtPassword, "password")
  .click(LoginPage.btnLogin, HomePage.class);
}
```

by extending class, and providing a java class object, you can use reflection to use some sort of transversal to make sure each "HomePage.java" member is available on the page before continuing.

This would use something like the "waitForCondition" method to achieve this.

It's all up to you, since the PageObject pattern is just that. A pattern.  Many people recommend it, and many people do not.  It all depends on whether if you'd like to use the pattern.

As i've said before, using this pattern i have presented above, I've created a framework that housed around 3,000 tests running every day which had saved over 8+ man years of testing.

---

If you're deadset on using the PageObject pattern, it shouldn't be "too" difficult to incorporate it into conductor.

**Comment by ddavison** [comment]
(sorry, didn't mean to close.

**Comment by Alexeggers** [comment]
Hi @ddavison, thanks so much for replying so quickly. I should probably look at my github notifications more often than I do. I'll play around more with Conductor, it definitely gets a lot of work off my back! For now, I went without using Conductor in our "official" testing packages, but I'll experiment on another branch. Thanks again!

**Comment by ddavison** [comment]
sounds good!
